#!/bin/bash

# read the script location
SCRIPT=$(readlink -f $0)
DIR=`dirname $SCRIPT`
JQ=$DIR/lib/jq
PWD=`pwd`

if [ $# -eq 0 ]; then
  echo "No arguments supplied, please add session description in json"
  exit 1
fi

JSON=$1
NAME=$2

function startSession {
  local prefix="$1"
  local nameArg="$2"

  local name=`$JQ -r "$prefix.name // \"session\"" $JSON`
  local location=`$JQ -r "$prefix.location // \"$PWD\"" $JSON`

  local windowName=`$JQ -r "$prefix.open[0].name" $JSON`

  name=${nameArg:-$name}

  # Location if ~ is part of the path
  tmux new-session -d -c $location -n $windowName -s $name

  # TODO deal with errors
  echo $name
}

function addWindows {
  local prefix="$1"
  local session="$2"

  local length=`$JQ "$prefix.open | length - 1" $JSON`
  echo "I need to create $length windows"

  local i=0
  while [ $i -lt $length ]
  do
    i=$[$i+1]
    addWindow "$prefix.open[$i]" $session $i
  done
}

function addWindow {
  local prefix="$1"
  local session="$2"
  local session="$3"

  local name=`$JQ "$prefix.name" $JSON`
  local open=`$JQ "${prefix}.open" $JSON`

  tmux new-window -t "$session" -k -n $name
}

function attachSession {
  tmux attach -t $1
}

session=`startSession '' $NAME`
addWindows '' $session
attachSession $session
