#!/bin/bash

# read the script location
SCRIPT=$(readlink -f $0)
DIR=`dirname $SCRIPT`
JQ=$DIR/lib/jq
PWD=`pwd`

if [ $# -eq 0 ]; then
  echo "No arguments supplied, please add session description in json"
  exit 1
fi

JSON=$1
NAME=$2

function startSession {
  local prefix="$1"
  local nameArg="$2"

  local name=`$JQ -r "$prefix.name // \"session\"" $JSON`
  local location=`$JQ -r "$prefix.location // \"$PWD\"" $JSON`

  local windowName=`$JQ -r "$prefix.open[0].name" $JSON`

  name=${nameArg:-$name}

  # ensure session name is unic
  sessions=`tmux ls -F '#{session_name}'`
  if [[ $sessions == *"$name"* ]]
  then
    >&2 echo "the session name $name is already used!"
    return 1;
  fi

  # TODO expand ~ to home path
  tmux new-session -d -c $location -n $windowName -s $name
  tmux send-keys -t $session:0 "unset TMUX" C-m
  tmux send-keys -t $session:0 "clear" C-m

  # TODO deal with errors
  echo $name
}

function addWindows {
  local prefix="$1"
  local session="$2"

  local length=`$JQ "$prefix.open | length - 1" $JSON`
  echo "I need to create $length windows"

  local i=0
  while [ $i -lt $length ]
  do
    i=$[$i+1]
    addWindow "$prefix.open[$i]" $session $i
  done
}

function addWindow {
  local prefix="$1"
  local session="$2"
  local windowNo="$3"

  local name=`$JQ "$prefix.name" $JSON`
  local open=`$JQ "${prefix}.open" $JSON`

  tmux new-window -t "$session" -k -n $name
  tmux send-keys -t $session:$windowNo "unset TMUX" C-m;
  tmux send-keys -t $session:$windowNo "clear" C-m;
}

function attachSession {
  tmux attach -t $1
}

session=`startSession '' $NAME` || {
  echo 'Failed to init root session, exiting'
  exit
}

addWindows '' $session
attachSession $session
